# Generated by Django 6.0.3 on 2026-03-12 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aspiration Category',
                'db_table': 'asp_category',
            },
        ),
        migrations.CreateModel(
            name='Aspiration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai'), ('proses', 'Proses'), ('dibatalkan', 'Dibatalkan')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/aspiration/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='assets/aspiration/videos')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='asp_aspirations', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirations', to='aspiration.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AspirationProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai'), ('proses', 'Proses'), ('dibatalkan', 'Dibatalkan')], max_length=50)),
                ('description', models.TextField()),
                ('aspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='aspiration.aspiration')),
            ],
            options={
                'verbose_name': 'Aspiration Progress',
                'db_table': 'asp_aspiration_progress',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('aspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='aspiration.aspiration')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aspiration Notification',
                'db_table': 'asp_notification',
            },
        ),
    ]
