# Generated by Django 6.0.3 on 2026-03-12 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspiration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspirationprogress',
            options={'verbose_name': 'Aspiration Progress', 'verbose_name_plural': 'Aspiration Progress'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Aspiration Category', 'verbose_name_plural': 'Aspiration Categories'},
        ),
        migrations.AddField(
            model_name='aspirationprogress',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
