# Generated by Django 6.0.3 on 2026-03-14 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspiration', '0002_alter_aspirationprogress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspiration',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aspiration',
            name='video',
        ),
        migrations.CreateModel(
            name='AspirationFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='aspiration/attachments/')),
                ('aspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='aspiration.aspiration')),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_attachments', to='aspiration.aspirationprogress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
