# Generated by Django 6.0.3 on 2026-03-26 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspiration', '0003_remove_aspiration_image_remove_aspiration_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Aspiration Location',
                'db_table': 'asp_location',
            },
        ),
        migrations.AlterField(
            model_name='aspirationfile',
            name='file',
            field=models.FileField(upload_to='assets/aspiration/attachments/'),
        ),
        migrations.AlterField(
            model_name='aspiration',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirations', to='aspiration.location'),
        ),
    ]
