# Generated by Django 6.0.3 on 2026-03-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/user/images'),
        ),
    ]
